channels:
  - conda-forge

dependencies:
  - python=3.10.12
  - pip=23.2.1                   
  - robocorp-truststore=0.8.0
  - pip:
    - selenium==4.15.2
    - requests==2.32.3
    - pandas==2.2.2
    - python-dateutil==2.9.0.post0
    - rpaframework==28.6.2